server:
  address: tcp://0.0.0.0:9091
log:
  level: info
identity_validation:
  reset_password:
    jwt_secret: ${AUTHELIA_JWT_SECRET}
authentication_backend:
  file:
    path: /config/users.yml
access_control:
  default_policy: deny
  rules:
    - domain: 
        - test.sandbox99.local
        - pastebin.sandbox99.local
      policy: one_factor
    - domain:
        - microbin.sandbox99.local
      policy: bypass

session:
  name: authelia_session
  secret: ${AUTHELIA_SESSION_SECRET}
  cookies:
    - domain: sandbox99.local
      authelia_url: https://auth0.sandbox99.local
storage:
  encryption_key: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
  local:
    path: /data/authelia.db
notifier:
  filesystem:
    filename: /config/notification.txt
